// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukXZQWf-hP90V2yY9UJm8X5zohLb8hh8',
    appId: '1:112016232680:web:5d1afe772f1e7ae31c795d',
    messagingSenderId: '112016232680',
    projectId: 'fitness-64939',
    authDomain: 'fitness-64939.firebaseapp.com',
    storageBucket: 'fitness-64939.firebasestorage.app',
    measurementId: 'G-7ZTMP4G6JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWL2pYYaSOEsNlYiuK7nix35nrzqXRYrI',
    appId: '1:112016232680:android:008c9f0521b867c01c795d',
    messagingSenderId: '112016232680',
    projectId: 'fitness-64939',
    storageBucket: 'fitness-64939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChW9pdAJEvOShHQneYCIdZvg1dNoMr--4',
    appId: '1:112016232680:ios:2bc8eb7b22a5443e1c795d',
    messagingSenderId: '112016232680',
    projectId: 'fitness-64939',
    storageBucket: 'fitness-64939.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChW9pdAJEvOShHQneYCIdZvg1dNoMr--4',
    appId: '1:112016232680:ios:2bc8eb7b22a5443e1c795d',
    messagingSenderId: '112016232680',
    projectId: 'fitness-64939',
    storageBucket: 'fitness-64939.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBukXZQWf-hP90V2yY9UJm8X5zohLb8hh8',
    appId: '1:112016232680:web:01dce9d714fb27bb1c795d',
    messagingSenderId: '112016232680',
    projectId: 'fitness-64939',
    authDomain: 'fitness-64939.firebaseapp.com',
    storageBucket: 'fitness-64939.firebasestorage.app',
    measurementId: 'G-FJS7XCMBFM',
  );
}
